cask_args appdir: '/Applications'

tap 'caskroom/cask'
tap 'homebrew/bundle'

brew 'sonar-runner'
brew 'python'
brew 'sbt'

cask 'java'
cask 'gitkraken'
cask 'slack'
cask 'mysqlworkbench'
cask 'p4merge'
cask 'intellij-idea'
cask 'macdown'
cask 'robomongo'
cask 'rdm'
